[package]
name = "para-genesis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crow = "0.7.2"
image = "0.24.8"
noise = "0.8.2"
rand = "0.8.5"
